
nippo_jp_en = {
    '日': 'day',
    '曜': 'weekday',
    '天気': 'weather',
    '売上(税込)': 'sales_tax_included',
    'カード売上': 'card_sales',
    'カード比率': 'card_ratio',
    '粗売上': 'gross_sales',
    '客組': 'guest_group',
    '客数': 'number_of_clients',
    '会員人数': 'number_of_members',
    '新規組数': 'new_guest_groups',
    'フリー組数': 'free_groups',
    'フリー人数': 'free_people',
    'フリー延長組数': 'free_extension_group_number',
    '指名率': 'nomination_rate',
    '延長率': 'extension_rate',
    '女子        総出勤時間': 'women_total_work_hours',
    '分配率': 'distribution_ratio',
    '男子        総出勤時間': 'men_total_work_hours',
    '分配率.1': 'distribution_ratio_1',
    '女子人数': 'number_of_women',
    '平均時間': 'average_time',
    '男子人数': 'number_of_men',
    '女子      生産性': 'women_productivity',
    '男子      生産性': 'men_productivity',
    '社人': 'employee',
    '社時': 'company_time',
    'ア人': 'a_hito',
    'ア時': 'a_toki',
    'へ人': 'e_hito',
    'へ時': 'e_toki',
    'ド人': 'do_hito',
    'ド時': 'do_toki',
    '体入時間': 'entry_time',
    '延長組数': 'number_extended_sits',
    '延長時間': 'extension_time',
    'A指名組数': 'a_nomination_groups_number',
    'Ａ指名本数': 'a_nomination_number',
    'B指名組数': 'b_nomination_groups_number',
    'Ｂ指名本数': 'b_nomination_number',
    '同伴組数': 'accompanied_groups_number',
    '電': 'den',
    '面': 'tsura',
    '客単価(税込)': 'price_per_customer_tax_included',
    '現金在高': 'cash_balance'
    }
