assis_jp_en ={
    '店番': 'store_number',
    '店名': 'store_name',
    '源氏名': 'hostess_name',
    '本名': 'real_name',
    '職種区分': 'job_category',
    'CP  コード': 'cp_code',
    '給与システム': 'payroll_system',
    '保証時給': 'guaranteed_hourly_rate',
    'スライド時給': 'slide_hourly_rate',
    '売上スライド': 'earnings_slide',
    '平均時給': 'average_hourly_wage',
    '勤務日数': 'working_days',
    '勤務時間': 'working_hours',
    '出勤時間': 'start_time',
    '退勤時間': 'leave_time',
    '欠勤': 'absence',
    '欠勤金額': 'absence_amount',
    '遅刻': 'late_comming',
    '遅刻金額': 'late_amount',
    '売上': 'earnings',
    '売上小計': 'earnings_subtotal',
    '売上(税抜）': 'earnings_excluding_tax',
    'カスタムの列1': 'custom_column_1',
    'カスタムの列2': 'custom_column_2',
    'カスタムの列3': 'custom_column_3',
    'カスタムの列4': 'custom_column_4',
    'カスタムの列5': 'custom_column_5',
    '仮払': 'salary_advance',
    'ボトル金額(売上小計)': 'bottle_value_subtotal_earnings',
    'ドリンク金額(売上小計)': 'drink_amount_subtotal_earnings',
    'フード金額(売上小計)': 'food_amount_earnings_subtotal',
    'ボトル金額': 'bottle_amount',
    'ボトル数(個)': 'number_of_bottles_pieces',
    'ボトル金額(個)': 'bottle_amount_pcs',
    'ボトル数(セ)': 'number_of_bottles_store',
    'ボトル金額(セ)': 'bottle_amounts',
    'ボトルA数(セ)': 'bottle_a_number_store',
    'ボトルA金額(セ)': 'bottle_a_amount_store',
    'ボトルB数(セ)': 'number_of_bottles_b_store',
    'ボトルB金額(セ)': 'bottle_b_amount_store',
    'ボトルC数(セ)': 'bottle_c_number_store',
    'ボトルC金額(セ)': 'bottle_c_amount_c',
    'ボトルD数(セ)': 'bottle_d_number_store',
    'ボトルD金額(セ)': 'bottle_d_amount_store',
    'ボトルE数(セ)': 'number_of_bottles_e',
    'ボトルE金額(セ)': 'bottle_e_amount_store',
    'チャージ金額': 'charge_amount',
    'ドリンク杯数(個)': 'number_of_drinks_pieces',
    'ドリンク金額(個)': 'drink_amount_pieces',
    'ドリンクA杯数(セ)': 'number_of_drink_a_cups_store',
    'ドリンクA金額(セ)': 'drink_a_amount_store',
    'ドリンクB杯数(セ)': 'number_of_b_drinks_store',
    'ドリンクB金額(セ)': 'drink_b_amount_store',
    'ドリンクC杯数(セ)': 'number_of_drinks_c',
    'ドリンクC金額(セ)': 'drink_c_amount_store',
    'ドリンクD杯数(セ)': 'number_of_d_drinks_store',
    'ドリンクD金額(セ)': 'drink_d_amount_store',
    'ドリンクE杯数(セ)': 'number_of_drink_e_cups_store',
    'ドリンクE金額(セ)': 'drink_e_amount_store',
    'ドリンクF杯数(セ)': 'number_of_drinks_f_store',
    'ドリンクF金額(セ)': 'drink_f_amount_store',
    'フード数(個)': 'number_of_hoods_pcs',
    'フード金額(個)': 'food_amount_pieces',
    'フード数(セ)': 'number_of_hoods_store',
    'フード金額(セ)': 'food_amounts',
    'B指名金額(個)': 'b_nomination_amount_pieces',
    '原価': 'cost_price',
    'バック': 'back',
    'A指名組': 'a_nomination_group',
    'A指名組(本指名1)': 'a_nomination_group_main_nomination_1',
    'A指名組(本指名2)': 'a_nomination_group_main_nomination_2',
    'A指名組(本指名3)': 'a_nomination_group_main_nomination_3',
    'A指名組(本指名4)': 'a_nomination_group_main_nomination_4',
    'A指名': 'a_nomination',
    'A指名(本指名1)': 'a_nomination_main_nomination_1',
    'A指名(本指名2)': 'a_nomination_main_nomination_2',
    'A指名(本指名3)': 'a_nomination_main_nomination_3',
    'A指名(本指名4)': 'a_nomination_main_nomination_4',
    'B指名組': 'b_nomination_group',
    'B指名': 'b_nomination',
    'C指名組': 'c_nomination_group',
    'D指名組': 'd_nomination_group',
    'E指名組': 'e_nomination_group',
    'F指名組': 'f_nomination_group',
    'C指名': 'c_nomination',
    'D指名': 'd_nomination',
    'E指名': 'e_nomination',
    'F指名': 'f_nomination',
    '延長20分': 'extension_of_20_minutes',
    '延長40分': 'extension_of_40_minutes',
    '延長60分': 'extension_of_60_minutes',
    '延長20分(A指名)': 'extension_of_20_minutes_a_nomination',
    '延長20分(A指名)(本指名1)': 'extension_20_minutes_a_nomination_main_nomination_1',
    '延長20分(A指名)(本指名2)': 'extension_20_minutes_a_nomination_main_nomination_2',
    '延長20分(A指名)(本指名3)': 'extension_20_minutes_a_nomination_main_nomination_3',
    '延長20分(A指名)(本指名4)': 'extension_20_minutes_a_nomination_main_nomination_4',
    '延長40分(A指名)': 'extension_40_minutes_a_nomination',
    '延長40分(A指名)(本指名1)': 'extension_40_minutes_a_nomination_main_nomination_1',
    '延長40分(A指名)(本指名2)': 'extension_40_minutes_a_nomination_main_nomination_2',
    '延長40分(A指名)(本指名3)': 'extension_40_minutes_a_nomination_main_nomination_3',
    '延長40分(A指名)(本指名4)': 'extension_40_minutes_a_nomination_main_nomination_4',
    '延長60分(A指名)': 'extension_60_minutes_a_nomination',
    '延長60分(A指名)(本指名1)': 'extension_60_minutes_a_nomination_main_nomination_1',
    '延長60分(A指名)(本指名2)': 'extension_60_minutes_a_nomination_main_nomination_2',
    '延長60分(A指名)(本指名3)': 'extension_60_minutes_a_nomination_main_nomination_3',
    '延長60分(A指名)(本指名4)': 'extension_60_minutes_a_nomination_main_nomination_4',
    '延長20分(B指名)': 'extension_20_minutes_b_nomination',
    '延長40分(B指名)': 'extension_40_minutes_b_nomination',
    '延長60分(B指名)': 'extension_60_minutes_b_nomination',
    'A指名延長組(本指名1)': 'a_nomination_extension_group_main_nomination_1',
    'A指名延長組(本指名2)': 'a_nomination_extension_group_main_nomination_2',
    'A指名延長組(本指名3)': 'a_nomination_extension_group_main_nomination_3',
    'A指名延長組(本指名4)': 'a_nomination_extension_group_main_nomination_4',
    '同伴 A': 'accompanied_a',
    '同伴 B': 'accompanied_b',
    '同伴 C': 'accompanied_c',
    '同伴 D': 'accompanied_d',
    '同伴 E': 'accompanied_e',
    '同延 A': 'same_extension_a',
    '同延 A本': 'same_extension_a_main',
    '同延 B': 'same_extension_b',
    '同延 B本': 'same_extension_b_main',
    '同延 C': 'same_extension_c',
    '同延 D': 'same_extension_d',
    '同延 E': 'same_extension_e',
    '同伴A 売上': 'accompanied_a_earnings',
    '同伴B 売上': 'accompanied_b_earnings',
    '同伴C 売上': 'accompanied_c_earnings',
    '同伴D 売上': 'accompanied_d_earnings',
    '同伴E 売上': 'accompanied_e_earnings',
    '同伴A 売上小計': 'accompanied_a_earnings_subtotal',
    '同伴B 売上小計': 'accompanied_b_earnings_subtotal',
    '同伴C 売上小計': 'accompanied_c_earnings_subtotal',
    '同伴D 売上小計': 'accompanied_d_earnings_subtotal',
    '同伴E 売上小計': 'accompanied_e_earnings_subtotal',
    '同伴A ボトル小計': 'accompanied_a_bottle_subtotal',
    '同伴B ボトル小計': 'accompanied_b_bottle_subtotal',
    '同伴C ボトル小計': 'accompanied_c_bottle_subtotal',
    '同伴D ボトル小計': 'accompanied_d_bottle_subtotal',
    '同伴E ボトル小計': 'accompanied_e_bottle_subtotal',
    'その他': 'others',
    'A指名1売上小計': 'a_nomination_1_earnings_subtotal',
    'A指名2売上小計': 'a_nomination_2_earnings_subtotal',
    'A指名3売上小計': 'a_nomination_3_earnings_subtotal',
    'A指名4売上小計': 'a_nomination_4_earnings_subtotal',
    '入店经由区分': 'entering_store_category',
    'CPマスタ备考1': 'cp_master_review_1',
    'CPマスタ备考2': 'cp_master_review_2',
    'CP-No': 'cp_no'
    }
