import os

PROJECT_ID = os.environ["PROJECT_ID"]
DATASET = os.environ["DATASET"]
TABLE_1 = os.environ["TABLE_1"]
TABLE_2 = os.environ["TABLE_2"]
TABLE_3 = os.environ["TABLE_3"]
TABLE_4 = os.environ["TABLE_4"]
ORIGIN_BUCKET = os.environ["ORIGIN_BUCKET"]
DESTINATION_BUCKET = os.environ["DESTINATION_BUCKET"]

upload_dict = {
    "assis": TABLE_1,
    "nippo": TABLE_2,
    "shosai": TABLE_3,
    "goukei_data": TABLE_4,
}

gd_jp_en = {
    'オーダ番号': 'order_number',
    '会計番号': 'bill_number',
    '営業日': 'business_day',
    '来店時間': 'visit_time',
    '会計日': 'bill_date',
    '時刻': 'hour',
    '顧客名': 'customer_name',
    'テーブル名': 'table_name',
    '客数': 'number_of_customers',
    'A指名客数': 'a_denomination_customer',
    'フリー客数': 'number_of_free_customers',
    'CP名': 'hostess_name',
    'status名': 'status_name',
    '売上小計': 'sales_subtotal',
    '支払対象額': 'payable_amount',
    '補正額': 'correction_amount',
    '支払額': 'paid_amount',
    'クレジット支払額': 'credit_paid_amount',
    '現金支払額': 'cash_paid_amount',
    'クーポン支払額': 'coupon_paid_amount',
    '付け支払額': 'payment_amount',
    'お預り額': 'deposit_amount',
    'お釣り額': 'charge_amount',
    'STFコード': 'stf_code',
    '割引額': 'discount_amount',
    '領収書発行': 'receipt_issued',
    '立替項目': 'replacement_item',
    '顧客-No': 'customer_number'
}


gs_jp_en = {
    '営業日': 'business_day',
    'オーダ   番号': 'order_number',
    '会計    番号': 'bill_number',
    'シー      ケンス': 'sequence',
    'セット': 'set',
    'オーダ    種別': 'order_classification',
    'オーダ    コード': 'order_code',
    '品名': 'product_name',
    '単価': 'unit_price',
    '数量': 'number_units',
    '金額': 'total_amount',
    'CP (ボトル)': 'cp_bottle',
    'CPコード(ボトル)': 'cp_code_bottle',
    '担当CP': 'cp_in_charge'
    }


nippo_jp_en = {
    '日': 'day',
    '曜': 'weekday',
    '天気': 'weather',
    '売上(税込)': 'sales_tax_included',
    'カード売上': 'card_sales',
    'カード比率': 'card_ratio',
    '粗売上': 'gross_sales',
    '客組': 'guest_group',
    '客数': 'number_of_clients',
    '会員人数': 'number_of_members',
    '新規組数': 'new_guest_groups',
    'フリー組数': 'free_groups',
    'フリー人数': 'free_people',
    'フリー延長組数': 'free_extension_group_number',
    '指名率': 'nomination_rate',
    '延長率': 'extension_rate',
    '女子        総出勤時間': 'women_total_work_hours',
    '分配率': 'distribution_ratio',
    '男子        総出勤時間': 'men_total_work_hours',
    '分配率.1': 'distribution_ratio_1',
    '女子人数': 'number_of_women',
    '平均時間': 'average_time',
    '男子人数': 'number_of_men',
    '女子      生産性': 'women_productivity',
    '男子      生産性': 'men_productivity',
    '社人': 'employee',
    '社時': 'company_time',
    'ア人': 'a_hito',
    'ア時': 'a_toki',
    'へ人': 'e_hito',
    'へ時': 'e_toki',
    'ド人': 'do_hito',
    'ド時': 'do_toki',
    '体入時間': 'entry_time',
    '延長組数': 'number_extended_sits',
    '延長時間': 'extension_time',
    'A指名組数': 'a_nomination_groups_number',
    'Ａ指名本数': 'a_nomination_number',
    'B指名組数': 'b_nomination_groups_number',
    'Ｂ指名本数': 'b_nomination_number',
    '同伴組数': 'accompanied_groups_number',
    '電': 'den',
    '面': 'tsura',
    '客単価(税込)': 'price_per_customer_tax_included',
    '現金在高': 'cash_balance'
    }


assis_jp_en ={
    '店番': 'store_number',
    '店名': 'store_name',
    '源氏名': 'hostess_name',
    '本名': 'real_name',
    '職種区分': 'job_category',
    'CP  コード': 'cp_code',
    '給与システム': 'payroll_system',
    '保証時給': 'guaranteed_hourly_rate',
    'スライド時給': 'slide_hourly_rate',
    '売上スライド': 'earnings_slide',
    '平均時給': 'average_hourly_wage',
    '勤務日数': 'working_days',
    '勤務時間': 'working_hours',
    '出勤時間': 'start_time',
    '退勤時間': 'leave_time',
    '欠勤': 'absence',
    '欠勤金額': 'absence_amount',
    '遅刻': 'late_comming',
    '遅刻金額': 'late_amount',
    '売上': 'earnings',
    '売上小計': 'earnings_subtotal',
    '売上(税抜）': 'earnings_excluding_tax',
    'カスタムの列1': 'custom_column_1',
    'カスタムの列2': 'custom_column_2',
    'カスタムの列3': 'custom_column_3',
    'カスタムの列4': 'custom_column_4',
    'カスタムの列5': 'custom_column_5',
    '仮払': 'salary_advance',
    'ボトル金額(売上小計)': 'bottle_value_subtotal_earnings',
    'ドリンク金額(売上小計)': 'drink_amount_subtotal_earnings',
    'フード金額(売上小計)': 'food_amount_earnings_subtotal',
    'ボトル金額': 'bottle_amount',
    'ボトル数(個)': 'number_of_bottles_pieces',
    'ボトル金額(個)': 'bottle_amount_pcs',
    'ボトル数(セ)': 'number_of_bottles_store',
    'ボトル金額(セ)': 'bottle_amounts',
    'ボトルA数(セ)': 'bottle_a_number_store',
    'ボトルA金額(セ)': 'bottle_a_amount_store',
    'ボトルB数(セ)': 'number_of_bottles_b_store',
    'ボトルB金額(セ)': 'bottle_b_amount_store',
    'ボトルC数(セ)': 'bottle_c_number_store',
    'ボトルC金額(セ)': 'bottle_c_amount_c',
    'ボトルD数(セ)': 'bottle_d_number_store',
    'ボトルD金額(セ)': 'bottle_d_amount_store',
    'ボトルE数(セ)': 'number_of_bottles_e',
    'ボトルE金額(セ)': 'bottle_e_amount_store',
    'チャージ金額': 'charge_amount',
    'ドリンク杯数(個)': 'number_of_drinks_pieces',
    'ドリンク金額(個)': 'drink_amount_pieces',
    'ドリンクA杯数(セ)': 'number_of_drink_a_cups_store',
    'ドリンクA金額(セ)': 'drink_a_amount_store',
    'ドリンクB杯数(セ)': 'number_of_b_drinks_store',
    'ドリンクB金額(セ)': 'drink_b_amount_store',
    'ドリンクC杯数(セ)': 'number_of_drinks_c',
    'ドリンクC金額(セ)': 'drink_c_amount_store',
    'ドリンクD杯数(セ)': 'number_of_d_drinks_store',
    'ドリンクD金額(セ)': 'drink_d_amount_store',
    'ドリンクE杯数(セ)': 'number_of_drink_e_cups_store',
    'ドリンクE金額(セ)': 'drink_e_amount_store',
    'ドリンクF杯数(セ)': 'number_of_drinks_f_store',
    'ドリンクF金額(セ)': 'drink_f_amount_store',
    'フード数(個)': 'number_of_hoods_pcs',
    'フード金額(個)': 'food_amount_pieces',
    'フード数(セ)': 'number_of_hoods_store',
    'フード金額(セ)': 'food_amounts',
    'B指名金額(個)': 'b_nomination_amount_pieces',
    '原価': 'cost_price',
    'バック': 'back',
    'A指名組': 'a_nomination_group',
    'A指名組(本指名1)': 'a_nomination_group_main_nomination_1',
    'A指名組(本指名2)': 'a_nomination_group_main_nomination_2',
    'A指名組(本指名3)': 'a_nomination_group_main_nomination_3',
    'A指名組(本指名4)': 'a_nomination_group_main_nomination_4',
    'A指名': 'a_nomination',
    'A指名(本指名1)': 'a_nomination_main_nomination_1',
    'A指名(本指名2)': 'a_nomination_main_nomination_2',
    'A指名(本指名3)': 'a_nomination_main_nomination_3',
    'A指名(本指名4)': 'a_nomination_main_nomination_4',
    'B指名組': 'b_nomination_group',
    'B指名': 'b_nomination',
    'C指名組': 'c_nomination_group',
    'D指名組': 'd_nomination_group',
    'E指名組': 'e_nomination_group',
    'F指名組': 'f_nomination_group',
    'C指名': 'c_nomination',
    'D指名': 'd_nomination',
    'E指名': 'e_nomination',
    'F指名': 'f_nomination',
    '延長20分': 'extension_of_20_minutes',
    '延長40分': 'extension_of_40_minutes',
    '延長60分': 'extension_of_60_minutes',
    '延長20分(A指名)': 'extension_of_20_minutes_a_nomination',
    '延長20分(A指名)(本指名1)': 'extension_20_minutes_a_nomination_main_nomination_1',
    '延長20分(A指名)(本指名2)': 'extension_20_minutes_a_nomination_main_nomination_2',
    '延長20分(A指名)(本指名3)': 'extension_20_minutes_a_nomination_main_nomination_3',
    '延長20分(A指名)(本指名4)': 'extension_20_minutes_a_nomination_main_nomination_4',
    '延長40分(A指名)': 'extension_40_minutes_a_nomination',
    '延長40分(A指名)(本指名1)': 'extension_40_minutes_a_nomination_main_nomination_1',
    '延長40分(A指名)(本指名2)': 'extension_40_minutes_a_nomination_main_nomination_2',
    '延長40分(A指名)(本指名3)': 'extension_40_minutes_a_nomination_main_nomination_3',
    '延長40分(A指名)(本指名4)': 'extension_40_minutes_a_nomination_main_nomination_4',
    '延長60分(A指名)': 'extension_60_minutes_a_nomination',
    '延長60分(A指名)(本指名1)': 'extension_60_minutes_a_nomination_main_nomination_1',
    '延長60分(A指名)(本指名2)': 'extension_60_minutes_a_nomination_main_nomination_2',
    '延長60分(A指名)(本指名3)': 'extension_60_minutes_a_nomination_main_nomination_3',
    '延長60分(A指名)(本指名4)': 'extension_60_minutes_a_nomination_main_nomination_4',
    '延長20分(B指名)': 'extension_20_minutes_b_nomination',
    '延長40分(B指名)': 'extension_40_minutes_b_nomination',
    '延長60分(B指名)': 'extension_60_minutes_b_nomination',
    'A指名延長組(本指名1)': 'a_nomination_extension_group_main_nomination_1',
    'A指名延長組(本指名2)': 'a_nomination_extension_group_main_nomination_2',
    'A指名延長組(本指名3)': 'a_nomination_extension_group_main_nomination_3',
    'A指名延長組(本指名4)': 'a_nomination_extension_group_main_nomination_4',
    '同伴 A': 'accompanied_a',
    '同伴 B': 'accompanied_b',
    '同伴 C': 'accompanied_c',
    '同伴 D': 'accompanied_d',
    '同伴 E': 'accompanied_e',
    '同延 A': 'same_extension_a',
    '同延 A本': 'same_extension_a_main',
    '同延 B': 'same_extension_b',
    '同延 B本': 'same_extension_b_main',
    '同延 C': 'same_extension_c',
    '同延 D': 'same_extension_d',
    '同延 E': 'same_extension_e',
    '同伴A 売上': 'accompanied_a_earnings',
    '同伴B 売上': 'accompanied_b_earnings',
    '同伴C 売上': 'accompanied_c_earnings',
    '同伴D 売上': 'accompanied_d_earnings',
    '同伴E 売上': 'accompanied_e_earnings',
    '同伴A 売上小計': 'accompanied_a_earnings_subtotal',
    '同伴B 売上小計': 'accompanied_b_earnings_subtotal',
    '同伴C 売上小計': 'accompanied_c_earnings_subtotal',
    '同伴D 売上小計': 'accompanied_d_earnings_subtotal',
    '同伴E 売上小計': 'accompanied_e_earnings_subtotal',
    '同伴A ボトル小計': 'accompanied_a_bottle_subtotal',
    '同伴B ボトル小計': 'accompanied_b_bottle_subtotal',
    '同伴C ボトル小計': 'accompanied_c_bottle_subtotal',
    '同伴D ボトル小計': 'accompanied_d_bottle_subtotal',
    '同伴E ボトル小計': 'accompanied_e_bottle_subtotal',
    'その他': 'others',
    'A指名1売上小計': 'a_nomination_1_earnings_subtotal',
    'A指名2売上小計': 'a_nomination_2_earnings_subtotal',
    'A指名3売上小計': 'a_nomination_3_earnings_subtotal',
    'A指名4売上小計': 'a_nomination_4_earnings_subtotal',
    '入店经由区分': 'entering_store_category',
    'CPマスタ备考1': 'cp_master_review_1',
    'CPマスタ备考2': 'cp_master_review_2',
    'CP-No': 'cp_no'
    }
